@startuml

!include ../config.txt

title DOMAIN MODEL

scale 0.9
left to right direction
hide circle
hide empty fields
hide empty methods

rectangle "User's aggregate" {
    class ユーザー {
        + ユーザーID
        + 名前
        + Eメールアドレス
    }

    class ユーザーXXX {
        + propertyX
    }
}

ユーザーXXX --* ユーザー : コンポジション

note right of ユーザー
・メソッドは不要
・属性も全て書く必要なし
・「ルール・制約」を吹き出し内に記述
　　例：ユーザーは、XXの状態で作成される
end note

rectangle "Another aggregate" {
    class ClassA {
        + propertyA
        + propertyB
    }
    class ClassB {
        + propertyC
        + propertyD
    }
    class ClassC {
        + propertyA
        + propertyC
    }
}

ClassA --> ユーザー
ClassA -- ClassB
(ClassA, ClassB) .. ClassC : 関連

@enduml
