@startuml

!include ./config.txt

title Architecture

'-----------
rectangle "Presentation Layer" as presentation #FFF9ED

note left of (presentation)
* Endpoint
* Validation　
  * JSON Schema
* Mapping input data
end note

'-----------
rectangle "Infrastructure Layer" as infra #FEEEEB

note right of (infra)
* Repository
* Query Service (CQRS Read)
* External System
* Authentication
end note

'-----------
rectangle "Application Layer" as app #D1EEF9

note left of (app)
* Use case
---
* Query Service Interface (CQRS Read) & DTO
* Authentication Interface & Session Object ??
end note

'-----------
rectangle "Domain Layer" as domain #CDF3EA

note right of (domain)
* Value Object
  * ID, Name ...
* Model
  * Aggregate
* Domain Service
  * Exist check ...
* Factory
  * Policy ...
---
* Repository Interface
* External System Interface
  * Mail ...
end note

'-----------
http ..> presentation
cli ..> presentation
presentation --> app
infra --|> app
app --> domain
infra --|> domain

'-----------
note as notice
* "What" は Use Case 層に、"How" は、Model層に記述されているのが理想
* Model のコンストラクタは新規専用。再構築用メソッドは別にする
end note

@enduml
