@startuml

!include ./config.txt

scale 0.9
hide empty description

title development flow

state "ユースケース図作成" as uml_usecase
state "モデル図作成\n（集約の明示化、ドメイン知識）" as uml_model
state "ドメイン層のテスト作成\n（Model, DomainService）" as test_domain
state "アプリケーション層のテスト作成\n（UseCase）" as test_application
state "ドメイン層の実装作成" as impl_domain
state "アプリケーション層の実装作成" as impl_application

[*] --> uml_usecase : No1

uml_usecase --> uml_model : No2

uml_model --> test_domain : No3

test_domain --> impl_domain : No4
impl_domain --> test_domain : No5

uml_usecase --> test_application : No6

test_application --> impl_application : No7
impl_application --> test_application : No8

impl_application --> [*] : End

@enduml
